### ISSUE TITLE
Lack of support for uniform[1-4]iu?v set of gl functions

### ISSUE THREAD

**Issue by andrey-zakharov** [fabmax/kool#15]
```
void glUniform1iv(GLint location, GLsizei count, const GLint *value);
void glUniform2iv(GLint location, GLsizei count, const GLint *value);
void glUniform3iv(GLint location, GLsizei count, const GLint *value);
void glUniform4iv(GLint location, GLsizei count, const GLint *value);
void glUniform1uiv(GLint location, GLsizei count, const GLuint *value);
void glUniform2uiv(GLint location, GLsizei count, const GLuint *value);
void glUniform3uiv(GLint location, GLsizei count, const GLuint *value);
void glUniform4uiv(GLint location, GLsizei count, const GLuint *value);
```

does they exists in Vulkan? IDK.
workaround: use `fv` with converting.

**Comment by fabmax** [comment]
Ah I probably did not implement them because I never needed them, should be pretty straight forward though

**Comment by fabmax** [comment]
I just wanted to check / fix this and realized that the uniform[*]iv mappings already exist since a while. Am I missing something?

Only the unsigned variants are not implemented yet (and I will keep it that way for now, because the signed integer versions should work fine almost always)
