### ISSUE TITLE
Font from bitmap

### ISSUE THREAD

**Issue by andrey-zakharov** [fabmax/kool#17]
I have tileset (bitmap) of chars. I do not see the way to make a font from it. 
The only what i want is to provide assetPath, and valid chars as char association map with tile index (or even more precise - exact region in bitmap for not-monospaced fonts) in it. Looks like `Font` currently draw this tileset for itself internally, and i want to provide this tileset by asset.

**Comment by fabmax** [comment]
By the way, this should work now by creating an `AtlasFont` and setting a manually created `FontMap` containing the font texture and char metrics. It might be a bit cumbersome to set up though.
