### ISSUE TITLE
Older Mac, GLView says I have 4.1, but hello world says I have 2.1?

### ISSUE THREAD

**Issue by salamanders** [fabmax/kool#28]
Exception in thread "main" de.fabmax.kool.KoolException: Minimum required OpenGL version is 3.3 but system version is 2.1

Which is strange, because GLView says I have 4.1.

**Comment by fabmax** [comment]
The OpenGL version is directly parsed from the corresponding OpenGL API call ([here](https://github.com/fabmax/kool/blob/main/kool-core/src/jvmMain/kotlin/de/fabmax/kool/platform/gl/GlRenderBackend.kt#L71)). If that resolves to 2.1 it is either parsed wrong or something else is odd.

You can try to comment / remove the exception and see what happens. However, OpenGL support on Mac OS is deprecated for quite a while so 2.1 might actually be the correct value.

**Comment by salamanders** [comment]
Yikes, well, sounds like WAI.  Thank you for checking!
