### ISSUE TITLE
Your project is incredible, great work it will be perfect for my first person shooter tests !! Thank you very much

### ISSUE THREAD

**Issue by Protoxy22** [fabmax/kool#3]

**Comment by fabmax** [comment]
Thanks! I'm glad you like it 😄

**Comment by fabmax** [comment]
Oh and keep me updated about your project, if you like.

In case you also wanna use physics for your project, you should take a look at the CharacterController class to control your ego character. However, I haven't really used that one myself (apart from some very basic testing) and some necessary stuff might still be missing.

**Comment by Protoxy22** [comment]
Yes I've seen the CharacterController class thanks 👍 I keep you tuned about my upcoming project, it will obviously take some time :)

**Comment by Protoxy22** [comment]
Hi, I have some difficulties to "attach" an object to the camera.
I've tried different matrix transformations, but I think I'm missing something

Here is my code
![image](https://user-images.githubusercontent.com/30320751/135897149-31315872-c2a1-45e6-bae8-bce35abad9e7.png)

gunModel is a Model _(you could imagine that)_

Here is a the result:
https://streamable.com/c9sq26
