### ISSUE TITLE
[Suggestion] LOD terrain example

### ISSUE THREAD

**Issue by Protoxy22** [fabmax/kool#33]
I think it could be interesting to make a real-time terrain LOD system.

Links:
https://svnte.se/cdlod-terrain

**Comment by fabmax** [comment]
Yes for larger terrains something like this is needed. But I think it's not super easy to get this right especially together with physics. For the physics meshes it's probably best to stick to the highest lod and simply remove nodes which are far away from the camera / player.

Anyway, I probably won't have anytime soon to put something like this together.
