### ISSUE TITLE
(help wanted) "Attach" a model to the CharacterTrackingCamRig

### ISSUE THREAD

**Issue by Protoxy22** [fabmax/kool#5]
Hi, I have some difficulties to "attach" an object to the camera.
I've tried different matrix transformations, but I think I'm missing something

Here is my code:
![image](https://cdn.discordapp.com/attachments/439513452629983240/894629785379160084/unknown.png)

gunModel is a Model (you could imagine that)

Here is a the result:
https://streamable.com/c9sq26

I also tested to translate to the real camera position by translating X by 0.8

I have read different tutorials about transformations, but I can't figure it out.
Thank you very much for your work

PS: I asked the last week for an arm64 compatibility, I succeeded to build the bindings + natives, but there was too much problems to solve with opengl / lwjgl 3.3.0. I'll try to continue later, I'll content to Windows for now

**Comment by Protoxy22** [comment]
Found it ! I had to use the camera position instead of the character

![image](https://user-images.githubusercontent.com/30320751/135918688-242a0d7c-7160-4a85-8311-8f5911d5c217.png)

https://streamable.com/bplrek

I just have some glitches when I sprint or moves, I could use a linear interpolation to fix it

**Comment by fabmax** [comment]
Looks nice! Another, maybe simpler, solution is to put your camera and your model into a `Group` and only move that group around. This way, camera and gun are in the same reference frame and should always have the same orientation and distance.

For the broken sky: I just noticed this in my [tree demo](https://fabmax.github.io/kool/kool-js/?demo=tree) as well. I guess I broke that some time ago when I fiddeled around with the skybox generator.

**Comment by fabmax** [comment]
Sky is fixed!

**Comment by Protoxy22** [comment]
Cool, thanks for the fast reply. I will test with your solution tomorrow

Have a good night

**Comment by Protoxy22** [comment]
Do you know how can I disable this kind of blur/specular on my gun texture (the real-time PBR Methodoly)
I would like have a raw albedo textures

Thanks
Protoxy.

**Comment by Protoxy22** [comment]
> I assume your model is a gltf model? By default, the gltf loader creates a PbrShader for each mesh in the model and uses the textures included in the model. You should be able to take the shaders of the model meshes, cast them to PbrShader, and set or remove the textures as you like.
> 
> For your second question: No, there is not. But it shouldn't be too hard to start a second thread for that.

I think I have to switch a texture propertie from LINEAR to NEAREST, maybe the minFilter and magFilter

https://github.com/fabmax/kool/blob/92a0b4ac4485c96447a4cc50793003474bb07015/kool-core/src/commonMain/kotlin/de/fabmax/kool/pipeline/Texture.kt#L141
