### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by donaldr** [fabmax/kool#50]
From what I see in kool/input/PlatformInput.kt it appears that kool captures all keypresses in the document. I'm planning on using kool in a non fullscreen canvas that has other components on the page. It would be better to only capture keyboard when the canvas is in focus (using tabindex) or perhaps provide an option to do so.

**Comment by fabmax** [comment]
Good point, I [added](https://github.com/fabmax/kool/commit/69f2d90374a13144c04cd0014ba4a9b7bd986360) an option to allow that. Now, per-canvas key-events can be enabled like this (global document keye event capture remains the default):

```
fun main() = KoolApplication(
    KoolConfig(isGlobalKeyEventGrabbing = false)
) {
    // application code...
}
```

**Comment by donaldr** [comment]
Amazing! Is this change published to the Maven repository? Really looking
forward to diving deeper in to this library!

**Comment by fabmax** [comment]
It's included in the latest snapshot:

```
repositories {
    maven("https://oss.sonatype.org/content/repositories/snapshots")
}

dependencies {
    implementation("de.fabmax.kool:kool-core:0.12.0-SNAPSHOT")
    implementation("de.fabmax.kool:kool-physics:0.12.0-SNAPSHOT")
}
```
