### ISSUE TITLE
Scenes models rendering jitters when using CharacterTrackingCamRig

### ISSUE THREAD

**Issue by Protoxy22** [fabmax/kool#56]
Hi, on the Island demo and when I use CharacterTrackingCamRig in general, the objects jitters/glitch when moving the character position.

It is maybe due of the `camera.trackedPose` being set directly to `playerController.controller.actor.transform` which is handled by the physics engine and not interpolated with frames rendering (I'm not sure).

Thanks

**Comment by Protoxy22** [comment]
It would be good to also have more control over the CharacterControllerManager/CharacterController to have less hardcoded parameters such as height/radius capsule, jump mechanism.

This kind of parameters should better be in demos

**Comment by fabmax** [comment]
Hmm not sure how exactly you mean that. The camera should be attached to the tracked object (the player model), meaning that there shouldn't be any jitter for the player itself but maybe some for the surrounding objects. But it actually looks ok to me even with mismatching framerates between physics and graphics, what framerates do you have?

Getting smoother camera motion would either require syncing the physics simulation rate to the screen refresh rate or some sort of movement interpolation which is tricky to get right.

**Comment by fabmax** [comment]
Ah yes that makes sense. I even tried higher framerates but of course my monitor limits at 60Hz so I don't see any jitter even at high frame rates (I can see them in your video though).

`SimplePhysicsStepper` is always in sync with the frame rate but it comes with a few other disadvantages: First, it doesn't simulate in parallel to the rendering thread making it quite a bit slower. Second, I have the feeling that the non-constant physics step times result in slightly more unstable physics behavior. So in case you experience any weird physics behavior in the future you should try going back to the constant one first.

**Comment by Protoxy22** [comment]
Fine, thanks you
